# -*- coding: utf-8 -*-
#
# This file is part of hepcrawl.
# Copyright (C) 2017 CERN.
#
# hepcrawl is a free software; you can redistribute it and/or modify it
# under the terms of the Revised BSD License; see LICENSE file for
# more details.

version: '2.1'

services:
  pip:
    build:
      context: ${PWD}
      dockerfile: tests/Dockerfile.hepcrawl_py3
    image: hepcrawl_py3
    command: "true"
