# -*- coding: utf-8 -*-
#
# This file is part of hepcrawl.
# Copyright (C) 2017 CERN.
#
# hepcrawl is a free software; you can redistribute it and/or modify it
# under the terms of the Revised BSD License; see LICENSE file for
# more details.

version: '2.1'

services:
  pip:
    build:
      context: ${PWD}/tests
      dockerfile: Dockerfile.hepcrawl_base
    image: hepcrawl_base
    tty: true
    environment:
      - BASE_USER_UID=${BASE_USER_UID:-1000}
      - BASE_USER_GIT=${BASE_USER_GIT:-1000}
    command: bash -c "pip install -e .[all] && pip freeze"
    volumes:
      - ${DOCKER_DATA}/tmp/hepcrawl_venv:/hepcrawl_venv/
      - ${PWD}:/code/
